on:
  push:
    branches: [ main ]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Run flake8
        uses: github/codeql-action/init@v1
      - name: Format imports
        uses: ambv/black@v21.9b0
        with:
          args: .
