on:
  push:
    branches: [ main ]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
#       - name: Install dependencies
#         run: pip install -r requirements.txt
      - name: Run linters
        uses: PyCQA/flake8-action@v2
        with:
          max-line-length: 79
      - name: Sort imports
        uses: PyCQA/isort-action@v2
        with:
          profile: black
